[book]
authors = ["Qiang Wang"]
language = "en"
src = "docs"
title = "tva Documentation"

[output.html]
git-repository-url = "https://github.com/wang-q/tva"
edit-url-template = "https://github.com/wang-q/tva/edit/master/{path}"
