[package]
name = "tva"
version = "0.0.1"
authors = ["wang-q <wang-q@outlook.com>"]
description = "Tab-separated Values Assistant"
documentation = "https://github.com/wang-q/tva"
homepage = "https://github.com/wang-q/tva"
repository = "https://github.com/wang-q/tva"
readme = "README.md"
categories = ["command-line-utilities", "science"]
license = "MIT"
edition = "2021"
publish = false

[lib]
name = "tva"
path = "src/lib.rs"

[[bin]]
name = "tva"
path = "src/tva.rs"

[dependencies]
clap = { version = "4.3.12", features = ["cargo"] }
serde = "1.0.171"
serde_json = "1.0.103"
anyhow = "1.0.72"
regex = "1.9.1"
lazy_static = "1.4.0"
flate2 = "1.0.26"
itertools = "0.11.0"

petgraph = "0.6.3"
indexmap = "2.0.0"
rust-lapper = "1.1.0"
crossbeam = "0.8.2"
rust_xlsxwriter = "0.43.0"

intspan = "0.8.7"

rapidhash = { version = "1.4.0", features = ["rng"] }
csv = "1.3.1"
markdown-table-formatter = "0.3.0"

which = "4.4.0"
cmd_lib = "1.9.4"
tempfile = "3.6.0"
path-clean = "1.0.1"
unicode-segmentation = "1.12.0"

[build-dependencies]

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.3"

[profile.release]
lto = true
