name: Publish

on:
  push:
    tags:
      - '*'

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - name: Show GLIBC
        run: ldd --version
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Build
        run: cargo build --verbose --release
      - name: Create tarball
        run: tar cvfz tva.tar.gz target/release/tva
        shell: bash
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tva.tar.gz
          asset_name: tva-x86_64-unknown-linux-gnu.tar.gz
          tag: ${{ github.ref }}
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Build
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.12
        run: cargo build --verbose --release
      - name: Create tarball
        run: tar cvfz tva.tar.gz target/release/tva
        shell: bash
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tva.tar.gz
          asset_name: tva-x86_64-apple-darwin.tar.gz
          tag: ${{ github.ref }}
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Enable static CRT linkage
        run: |
          New-Item -ItemType Directory -Force -Path .cargo
          Set-Content -Path .cargo/config.toml -Value "[target.x86_64-pc-windows-msvc]"
          Add-Content -Path .cargo/config.toml -Value "rustflags = ['-Ctarget-feature=+crt-static']"
      - name: Build
        run: cargo build --verbose --release
      - name: Create zip
        run: Compress-Archive -DestinationPath ./tva.zip -Path ./target/release/tva.exe
        shell: powershell
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tva.zip
          asset_name: tva-x86_64-pc-windows-msvc.zip
          tag: ${{ github.ref }}
